version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://usuario:contraseña@db:5432/tu_basededatos

  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: tu_basededatos
    ports:
      - "5432:5432"